title: NotAnArtical
description: "It looks real. It's not. And that's what hits different."
baseurl: "/NotAnArtical"
url: "https://gamercr4cked.github.io"
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
